#!/bin/bash

if [ -L "$0" ]; then
  REALSCRIPT=`readlink "$0"`
else
  REALSCRIPT=$0
fi
REALDIR=`dirname "$REALSCRIPT"`/src
MAIN="$REALDIR/Main.hs"

if [ ! -d "$REALDIR" -o ! -f "$MAIN" ]; then
  echo "Could not find Main.hs in '$REALDIR'"
  exit 1
fi

if [ -d "$REALDIR/../.cabal-sandbox" ]; then
  RUNHASKELL="cabal --sandbox-config-file=$REALDIR/../cabal.sandbox.config exec -- runhaskell"
else
  RUNHASKELL="runhaskell"
fi

if [ -d "$REALDIR/../.cabal-sandbox" ]; then
  exec cabal --sandbox-config-file="$REALDIR/../cabal.sandbox.config" exec -- runhaskell -i"$REALDIR" "$REALDIR"/Main.hs "$@"
else
  exec runhaskell -i"$REALDIR" "$REALDIR"/Main.hs "$@"
fi
